# Site settings
title: 范星的博客
email: fan_xing_1990@sina.com
description: 菜鸟iOS开发
baseurl: "/blog"
url: "https://github.com/fanXing99"

author:
  name     : '范星'
  email    : fan_xing_1990@sina.com
  url      : https://github.com/fanXing99
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/fanXing99
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
#highlighter: rouge

permalink : /:title/

theme: jekyll-theme-midnight
